#!/usr/bin/env bash

set -euxo pipefail

nix-shell https://github.com/leanprover/lean4/archive/master.tar.gz -A nix --run '
  nix shell --tarball-ttl 0 github:Kha/lean4/whnf-matcher -c temci exec --config ./scripts/bench/temci-config.yml > /dev/null'
temci report --reporter codespeed2 |\
  jq '(.build | to_entries | group_by(.key | test("~")) | map(from_entries)) as $groups | .build = $groups[0] | . + ($groups[1] | map_values({instructions: .}))'
  # move file metrics starting with "~" from "build" to toplevel and assign them the "instructions" metric
